name: Publish to Nuget.org

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        
    - name: Restore dependencies
      working-directory: AzFormRecognizerToSQL
      run: dotnet restore
      
    - name: Build
      working-directory: AzFormRecognizerToSQL
      run: dotnet build --no-restore -c Release
      
    - name: Pack
      working-directory: AzFormRecognizerToSQL
      run: |
        dotnet pack -c Release
        
    - name: Publish
      working-directory: AzFormRecognizerToSQL/bin/Release
      run: |
        dotnet nuget push *.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
      
