name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: [ '6.0.x', '7.0.x' ]

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup ${{ matrix.dotnet }} .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet }}

    - name: Build Solution
      run: dotnet build
        
    - name: Test
      working-directory: AzFormRecognizerToSQL.Tests
      run: dotnet test
